#pragma once

struct CBinstruction {
	int valid_instruction;
	int clock_cycle;
	int machine_cycle;
	void (*action)(void);
	
	//unsigned char ticks;

} extern const CBinstructions[256];


static unsigned char rlc(unsigned char registro);
static unsigned char rrc(unsigned char registro);
static unsigned char rl(unsigned char registro);
static unsigned char rr(unsigned char registro);
static unsigned char sla(unsigned char registro);
static unsigned char sra(unsigned char registro);
static unsigned char swap(unsigned char registro);
static unsigned char srl(unsigned char registro);
static void bit(unsigned char bit, unsigned char registro);

void rlc_b(void);
void rlc_c(void);
void rlc_d(void);
void rlc_e(void);
void rlc_h(void);
void rlc_l(void);
void rlc_hl(void);
void rlc_a(void);
void rrc_b(void);
void rrc_c(void);
void rrc_d(void);
void rrc_e(void);
void rrc_h(void);
void rrc_l(void);
void rrc_hl(void);
void rrc_a(void);
void rl_b(void);
void rl_c(void);
void rl_d(void);
void rl_e(void);
void rl_h(void);
void rl_l(void);
void rl_hl(void);
void rl_a(void);
void rr_b(void);
void rr_c(void);
void rr_d(void);
void rr_e(void);
void rr_h(void);
void rr_l(void);
void rr_hl(void);
void rr_a(void);
void sla_b(void);
void sla_c(void);
void sla_d(void);
void sla_e(void);
void sla_h(void);
void sla_l(void);
void sla_hl(void);
void sla_a(void);
void sra_b(void);
void sra_c(void);
void sra_d(void);
void sra_e(void);
void sra_h(void);
void sra_l(void);
void sra_hl(void);
void sra_a(void);
void swap_b(void);
void swap_c(void);
void swap_d(void);
void swap_e(void);
void swap_h(void);
void swap_l(void);
void swap_hl(void);
void swap_a(void);
void srl_b(void);
void srl_c(void);
void srl_d(void);
void srl_e(void);
void srl_h(void);
void srl_l(void);
void srl_hl(void);
void srl_a(void);
void bit_0_b(void);
void bit_0_c(void);
void bit_0_d(void);
void bit_0_e(void);
void bit_0_h(void);
void bit_0_l(void);
void bit_0_hl(void);
void bit_0_a(void);
void bit_1_b(void);
void bit_1_c(void);
void bit_1_d(void);
void bit_1_e(void);
void bit_1_h(void);
void bit_1_l(void);
void bit_1_hl(void);
void bit_1_a(void);
void bit_2_b(void);
void bit_2_c(void);
void bit_2_d(void);
void bit_2_e(void);
void bit_2_h(void);
void bit_2_l(void);
void bit_2_hl(void);
void bit_2_a(void);
void bit_3_b(void);
void bit_3_c(void);
void bit_3_d(void);
void bit_3_e(void);
void bit_3_h(void);
void bit_3_l(void);
void bit_3_hl(void);
void bit_3_a(void);
void bit_4_b(void);
void bit_4_c(void);
void bit_4_d(void);
void bit_4_e(void);
void bit_4_h(void);
void bit_4_l(void);
void bit_4_hl(void);
void bit_4_a(void);
void bit_5_b(void);
void bit_5_c(void);
void bit_5_d(void);
void bit_5_e(void);
void bit_5_h(void);
void bit_5_l(void);
void bit_5_hl(void);
void bit_5_a(void);
void bit_6_b(void);
void bit_6_c(void);
void bit_6_d(void);
void bit_6_e(void);
void bit_6_h(void);
void bit_6_l(void);
void bit_6_hl(void);
void bit_6_a(void);
void bit_7_b(void);
void bit_7_c(void);
void bit_7_d(void);
void bit_7_e(void);
void bit_7_h(void);
void bit_7_l(void);
void bit_7_hl(void);
void bit_7_a(void);